[package]
name = "chip-8-interpreter"
version = "0.1.0"
edition = "2021"

[dependencies]
ctrlc = "3.4.1"
rand = "0.8.5"

[dependencies.sdl2]
version = "0.35.2"
default-features = false
features = ["gfx"]
